export type MysterySubject = {
  answer: string
  aliases: string[]
  evidence: string
  contextualHint: string
  technicalHint: string
  nearAnswerHint: string
  explanation: string
}

export const locations = [
  'a closed neighborhood bank vestibule in Sao Paulo',
  'an empty municipal service office in Campinas',
  'a rain-streaked bus terminal corridor in Porto Alegre',
  'a shuttered lan house near a commuter station in Belo Horizonte',
  'a silent video rental store in Curitiba',
  'a dim lottery shop entrance in Recife',
  'a vacant university computer lab in Brasilia',
  'a forgotten telecom maintenance room in Rio de Janeiro',
  'a nearly empty twenty-four-hour pharmacy lobby in Goiania',
  'an abandoned commercial gallery passage in Salvador',
  'a closed post office waiting area in Manaus',
  'a wet subway mezzanine after the last train in Sao Paulo',
]

export const times = [
  '00:17',
  '00:43',
  '01:08',
  '01:26',
  '01:52',
  '02:11',
  '02:37',
  '02:58',
  '03:14',
  '03:39',
  '04:03',
  '04:28',
]

export const atmospheres = [
  'steady rain reflecting cold fluorescent tubes on worn tile',
  'a recent power fluctuation leaving one fluorescent tube faintly blinking',
  'humidity clouding the glass while distant traffic lights bleed into the floor',
  'a leaking ceiling marked by a plastic bucket and irregular concentric ripples',
  'a quiet ventilation hum under weak greenish fluorescent lighting',
  'rainwater dragged under a metal shutter and collecting beside old cables',
]

export const emotionalRegisters = [
  'the feeling that staff left ten minutes ago and never returned',
  'the melancholy of a routine interrupted without explanation',
  'a bureaucratic stillness preserved after closing time',
  'the residue of a place waiting for a system to reconnect',
  'the quiet embarrassment of obsolete technology still doing its job',
]

export const decades = [
  'late 1990s',
  'early 2000s',
  'mid 2000s',
  'late 2000s',
  'early 2010s',
  'late 2010s',
  'early 2020s',
]

export const subjects: MysterySubject[] = [
  {
    answer: 'orelhao',
    aliases: ['telefone publico', 'orelhao telefonico'],
    evidence: 'a blue public telephone shell with its handset resting slightly crooked',
    contextualHint: 'A chuva tambem sabia o numero de memoria.',
    technicalHint: 'Antes do celular, a rua tinha aparelhos compartilhados.',
    nearAnswerHint: 'A concha azul protegia uma ligacao curta e cara.',
    explanation: 'A concha azul, o monofone e a rua molhada apontam para o orelhao, antigo telefone publico brasileiro.',
  },
  {
    answer: 'disquete',
    aliases: ['floppy disk', 'disco flexivel', 'disquete 3.5'],
    evidence: 'a single 3.5-inch floppy disk beside a beige keyboard, its label unreadable',
    contextualHint: 'O arquivo inteiro cabia em um quadrado pequeno.',
    technicalHint: 'Sua capacidade era medida em poucos megabytes.',
    nearAnswerHint: 'A protecao rigida escondia um disco magnetico.',
    explanation: 'O pequeno quadrado plastico com lingueta metalica e um disquete de 3,5 polegadas.',
  },
  {
    answer: 'modem discado',
    aliases: ['modem 56k', 'internet discada', 'dial-up modem'],
    evidence: 'an external beige dial-up modem with tiny status lights and a telephone cable',
    contextualHint: 'Para entrar na rede, era preciso ocupar uma linha.',
    technicalHint: 'Os LEDs aguardavam uma negociacao ruidosa de conexao.',
    nearAnswerHint: 'A velocidade prometida era 56k.',
    explanation: 'O aparelho externo ligado a linha telefonica e um modem discado, porta de entrada da internet domestica dos anos 2000.',
  },
  {
    answer: 'impressora matricial',
    aliases: ['matricial', 'impressora de impacto'],
    evidence: 'a dot-matrix printer with continuous perforated paper curled onto the floor',
    contextualHint: 'O silencio da sala parece errado porque faltam impactos repetidos.',
    technicalHint: 'O papel avanca por furos laterais.',
    nearAnswerHint: 'Uma fita entintada recebia o golpe das agulhas.',
    explanation: 'O papel continuo perfurado e a fita de impacto identificam uma impressora matricial.',
  },
  {
    answer: 'cartao telefonico',
    aliases: ['cartao de orelhao', 'cartao indutivo'],
    evidence: 'a worn Brazilian inductive phone card abandoned near a public phone base',
    contextualHint: 'O credito ficava gasto fisicamente depois de algumas conversas.',
    technicalHint: 'Nao havia chip visivel nem tarja magnetica comum.',
    nearAnswerHint: 'Ele fazia o orelhao funcionar.',
    explanation: 'O cartao indutivo era usado nos orelhoes brasileiros e guardava unidades para ligacoes.',
  },
  {
    answer: 'pager',
    aliases: ['bip', 'beeper'],
    evidence: 'a small black numeric pager clipped to an empty plastic document tray',
    contextualHint: 'A mensagem chegava, mas a resposta precisava encontrar outro caminho.',
    technicalHint: 'Seu visor curto exibia numeros e codigos.',
    nearAnswerHint: 'Tambem era chamado de bip.',
    explanation: 'O pequeno receptor numerico preso a bandeja e um pager, conhecido no Brasil como bip.',
  },
  {
    answer: 'fax',
    aliases: ['aparelho de fax', 'fac-simile', 'facsimile'],
    evidence: 'a fax machine holding a curled thermal-paper transmission, with no readable content',
    contextualHint: 'Uma folha atravessou a madrugada pela linha telefonica.',
    technicalHint: 'A copia chegava devagar em papel termico.',
    nearAnswerHint: 'O documento era transmitido por telefone.',
    explanation: 'O rolo de papel termico e a conexao telefonica indicam um aparelho de fax.',
  },
  {
    answer: 'token bancario',
    aliases: ['token de banco', 'chave de seguranca', 'token digital'],
    evidence: 'a small bank security token with an inactive segmented LCD beside a payment slip',
    contextualHint: 'A senha mudava antes que alguem terminasse de copia-la.',
    technicalHint: 'O visor gerava codigos temporarios para acessar a conta.',
    nearAnswerHint: 'Era uma segunda chave para o internet banking.',
    explanation: 'O pequeno gerador de codigos temporarios e um token bancario fisico.',
  },
  {
    answer: 'boleto bancario',
    aliases: ['boleto', 'ficha de compensacao'],
    evidence: 'a damp payment slip with an obscured barcode resting beneath a service-window glass',
    contextualHint: 'A obrigacao venceu antes de a chuva parar.',
    technicalHint: 'A linha longa de numeros permitia pagar sem cartao.',
    nearAnswerHint: 'A ficha seguia para compensacao bancaria.',
    explanation: 'O comprovante com codigo de barras e linha numerica remete ao boleto bancario.',
  },
  {
    answer: 'caixa eletronico',
    aliases: ['atm', 'terminal de autoatendimento', 'caixa automatico'],
    evidence: 'an old ATM with a dark card slot and a dim idle screen reflected in rainwater',
    contextualHint: 'A agencia fechou, mas uma maquina continuou de plantao.',
    technicalHint: 'Ela aceitava cartao e entregava cedulas sem atendente.',
    nearAnswerHint: 'O autoatendimento ficava no vestibulo do banco.',
    explanation: 'A maquina de autoatendimento isolada na entrada bancaria e um caixa eletronico.',
  },
  {
    answer: 'maquina de xerox',
    aliases: ['xerox', 'fotocopiadora', 'copiadora'],
    evidence: 'a large office photocopier with its lid raised and one blank sheet in the output tray',
    contextualHint: 'A reparticao multiplicava papel mesmo depois do expediente.',
    technicalHint: 'Luz, toner e uma tampa pesada repetiam documentos.',
    nearAnswerHint: 'No Brasil, a marca virou nome da copia.',
    explanation: 'A copiadora de reparticao e reconhecida como maquina de xerox.',
  },
  {
    answer: 'ficha de orelhao',
    aliases: ['ficha telefonica', 'ficha de telefone'],
    evidence: 'a small grooved telephone token near an older orange public telephone',
    contextualHint: 'Antes do cartao, uma conversa custava uma pequena peca metalica.',
    technicalHint: 'Ela era inserida no telefone publico e consumida pela ligacao.',
    nearAnswerHint: 'Foi antecessora do cartao telefonico.',
    explanation: 'A ficha metalica junto ao telefone publico antigo antecede o cartao de orelhao.',
  },
  {
    answer: 'telex',
    aliases: ['terminal telex', 'teleimpressor'],
    evidence: 'a dusty teleprinter terminal with a narrow paper roll and mechanical keys',
    contextualHint: 'O escritorio recebia mensagens como quem recebia telegramas automaticos.',
    technicalHint: 'O terminal imprimia comunicacoes transmitidas por uma rede propria.',
    nearAnswerHint: 'Era mais antigo que o fax.',
    explanation: 'O teleimpressor com rolo estreito e teclado mecanico e um terminal de telex.',
  },
  {
    answer: 'crt',
    aliases: ['monitor crt', 'monitor de tubo', 'tubo de raios catodicos'],
    evidence: 'a bulky beige CRT monitor showing only a faint greenish reflection',
    contextualHint: 'A tela ocupava quase a profundidade inteira da mesa.',
    technicalHint: 'O vidro curvo escondia um tubo pesado.',
    nearAnswerHint: 'Antes das telas planas, o monitor tinha traseira enorme.',
    explanation: 'A tela curva e volumosa e um monitor CRT, conhecido como monitor de tubo.',
  },
  {
    answer: 'videocassete',
    aliases: ['vcr', 'video cassete', 'aparelho de vhs'],
    evidence: 'a black VCR with an empty tape slot beneath a small CRT television',
    contextualHint: 'A locadora fechou, mas uma fita ainda poderia ser rebobinada.',
    technicalHint: 'O aparelho gravava e reproduzia fitas magneticas.',
    nearAnswerHint: 'A abertura frontal recebia uma fita VHS.',
    explanation: 'O aparelho sob a TV, com abertura para fita VHS, e um videocassete.',
  },
  {
    answer: 'fita vhs',
    aliases: ['vhs', 'fita de video', 'fita videocassete'],
    evidence: 'an unlabeled VHS cassette half returned through a video-store drop slot',
    contextualHint: 'A devolucao chegou depois que a locadora deixou de existir.',
    technicalHint: 'Duas bobinas guardavam imagem e som magneticos.',
    nearAnswerHint: 'Era preciso rebobinar antes de devolver.',
    explanation: 'A fita com duas bobinas na portinhola da locadora e uma VHS.',
  },
  {
    answer: 'fita cassete',
    aliases: ['cassete', 'k7', 'fita k7'],
    evidence: 'a transparent audio cassette near a desk radio, its magnetic tape slightly slack',
    contextualHint: 'A madrugada ficou presa entre duas bobinas menores.',
    technicalHint: 'Uma caneta podia ajudar quando a fita afrouxava.',
    nearAnswerHint: 'Tambem era chamada de K7.',
    explanation: 'A fita magnetica compacta ao lado do radio e uma fita cassete ou K7.',
  },
  {
    answer: 'walkman',
    aliases: ['toca-fitas portatil', 'toca fitas portatil'],
    evidence: 'a scratched portable cassette player with foam headphones resting on a vinyl chair',
    contextualHint: 'A trilha sonora cabia no bolso do casaco esquecido.',
    technicalHint: 'O aparelho portatil reproduzia uma fita cassete.',
    nearAnswerHint: 'Fones leves e botoes mecanicos acompanhavam o Walkman.',
    explanation: 'O toca-fitas portatil com fones de espuma e reconhecido como Walkman.',
  },
  {
    answer: 'discman',
    aliases: ['cd player portatil', 'toca cd portatil'],
    evidence: 'a round portable CD player with its lid ajar beside wired earphones',
    contextualHint: 'Qualquer passo apressado fazia a musica hesitar.',
    technicalHint: 'Um disco optico girava dentro do aparelho portatil.',
    nearAnswerHint: 'Foi o sucessor do Walkman para CDs.',
    explanation: 'O aparelho redondo portatil com tampa para CD e um Discman.',
  },
  {
    answer: 'cd-rom',
    aliases: ['cd rom', 'compact disc read-only memory'],
    evidence: 'an iridescent CD-ROM beside a beige computer tower with an open optical tray',
    contextualHint: 'A instalacao esperava dentro de um circulo prateado.',
    technicalHint: 'A unidade lia dados opticos, mas nao precisava gravar.',
    nearAnswerHint: 'Muitos programas vinham em CD-ROM.',
    explanation: 'O disco de dados junto a bandeja optica e um CD-ROM.',
  },
  {
    answer: 'zip drive',
    aliases: ['unidade zip', 'zip disk', 'disco zip'],
    evidence: 'a blue external Zip drive and its thick removable disk beside a desktop computer',
    contextualHint: 'Era grande demais para um disquete e pequeno demais para permanecer.',
    technicalHint: 'A midia removivel oferecia dezenas ou centenas de megabytes.',
    nearAnswerHint: 'A unidade carregava o nome Zip.',
    explanation: 'A unidade externa azul e o disco espesso identificam o Zip drive.',
  },
  {
    answer: 'mouse de bolinha',
    aliases: ['mouse mecanico', 'mouse com bolinha'],
    evidence: 'an upside-down beige computer mouse exposing its removable rubber ball',
    contextualHint: 'A sujeira interrompia movimentos simples.',
    technicalHint: 'Dois eixos internos liam o giro de uma esfera.',
    nearAnswerHint: 'Antes do sensor optico, havia uma bolinha embaixo.',
    explanation: 'A esfera de borracha exposta indica um mouse mecanico, conhecido como mouse de bolinha.',
  },
  {
    answer: 'teclado abnt2',
    aliases: ['abnt2', 'teclado brasileiro'],
    evidence: 'a yellowed Brazilian keyboard with the distinctive extra key layout, no readable labels in focus',
    contextualHint: 'A mesa ainda lembrava que o idioma exigia uma tecla a mais.',
    technicalHint: 'O padrao brasileiro acomoda cedilha e acentos.',
    nearAnswerHint: 'Seu nome tecnico termina com o numero 2.',
    explanation: 'A disposicao brasileira de teclas aponta para o teclado ABNT2.',
  },
  {
    answer: 'estabilizador',
    aliases: ['estabilizador de tensao', 'estabilizador eletrico'],
    evidence: 'a beige voltage stabilizer with a red rocker switch under a computer desk',
    contextualHint: 'Toda inicializacao comecava por um clique sob a mesa.',
    technicalHint: 'O aparelho prometia suavizar variacoes da rede eletrica.',
    nearAnswerHint: 'Era comum ligar o computador por ele.',
    explanation: 'A caixa eletrica com interruptor vermelho sob a mesa e um estabilizador.',
  },
  {
    answer: 'nobreak',
    aliases: ['no-break', 'ups', 'fonte ininterrupta'],
    evidence: 'a heavy UPS unit under a service counter with one weak status light',
    contextualHint: 'Quando a luz falhava, alguns minutos ainda resistiam.',
    technicalHint: 'Uma bateria interna mantinha o terminal ligado brevemente.',
    nearAnswerHint: 'Ele evitava que a queda de energia encerrasse tudo de imediato.',
    explanation: 'A unidade com bateria sob o terminal e um nobreak.',
  },
  {
    answer: 'webcam',
    aliases: ['camera web', 'camera de computador'],
    evidence: 'an early spherical USB webcam perched on a CRT monitor facing an empty chair',
    contextualHint: 'A cadeira vazia ainda estava enquadrada.',
    technicalHint: 'A pequena camera enviava imagem pelo computador.',
    nearAnswerHint: 'Ela ficava sobre o monitor em chamadas pela internet.',
    explanation: 'A pequena camera presa ao monitor e uma webcam antiga.',
  },
  {
    answer: 'roteador',
    aliases: ['roteador wifi', 'router'],
    evidence: 'an early wireless router with two antennas and irregular blinking LEDs',
    contextualHint: 'A sala estava vazia, mas uma rede continuava respirando.',
    technicalHint: 'As antenas distribuam conexao sem fio aos dispositivos proximos.',
    nearAnswerHint: 'Ele roteava a internet local.',
    explanation: 'A caixa com antenas e LEDs e um roteador Wi-Fi.',
  },
  {
    answer: 'hub ethernet',
    aliases: ['hub de rede', 'hub'],
    evidence: 'a small Ethernet hub with several numbered ports and tangled blue network cables',
    contextualHint: 'Todas as maquinas ouviam o mesmo trafego.',
    technicalHint: 'Ele repetia pacotes para varias portas sem inteligencia de comutacao.',
    nearAnswerHint: 'Era mais simples que um switch.',
    explanation: 'A caixa de portas de rede compartilhadas e um hub Ethernet.',
  },
  {
    answer: 'cabo serial',
    aliases: ['serial', 'cabo rs-232', 'rs232'],
    evidence: 'a thick RS-232 serial cable with screw-fastened connectors coiled near an old terminal',
    contextualHint: 'A conexao exigia parafusos antes de exigir paciencia.',
    technicalHint: 'O conector transportava dados em serie entre equipamentos.',
    nearAnswerHint: 'O padrao tambem e conhecido como RS-232.',
    explanation: 'O conector largo preso por parafusos e um cabo serial RS-232.',
  },
  {
    answer: 'cabo paralelo',
    aliases: ['cabo de impressora', 'porta paralela', 'lpt'],
    evidence: 'a broad parallel printer cable linking a beige computer to a dot-matrix printer',
    contextualHint: 'O caminho ate o papel era largo e curto.',
    technicalHint: 'Muitos bits viajavam lado a lado ate a impressora.',
    nearAnswerHint: 'A porta do computador costumava ser chamada LPT.',
    explanation: 'O cabo largo entre computador e impressora e um cabo paralelo.',
  },
  {
    answer: 'leitor de codigo de barras',
    aliases: ['scanner de codigo de barras', 'leitor optico'],
    evidence: 'a wired handheld barcode scanner lying beside an empty checkout keyboard',
    contextualHint: 'A loja fechada ainda esperava um bip que nao viria.',
    technicalHint: 'Um feixe lia barras para identificar produtos.',
    nearAnswerHint: 'O caixa usava o leitor antes de cobrar.',
    explanation: 'O dispositivo manual com fio do caixa e um leitor de codigo de barras.',
  },
  {
    answer: 'maquininha de cartao',
    aliases: ['pos', 'terminal pos', 'maquina de cartao'],
    evidence: 'an old card payment terminal with a paper roll and a coiled telephone cable',
    contextualHint: 'A venda dependia de uma linha que podia estar ocupada.',
    technicalHint: 'O terminal imprimia comprovantes e autorizava pagamentos.',
    nearAnswerHint: 'Era a maquininha de cartao do balcão.',
    explanation: 'O terminal com teclado, bobina e cabo telefonico e uma maquininha de cartao antiga.',
  },
  {
    answer: 'dispensador de senha',
    aliases: ['chaveiro de senha', 'senha de atendimento', 'ticket de senha'],
    evidence: 'a small queue-ticket dispenser with one curled paper number protruding, digits unreadable',
    contextualHint: 'Mesmo sem ninguem, a espera tinha uma ordem.',
    technicalHint: 'Um pequeno papel determinava quem seria atendido primeiro.',
    nearAnswerHint: 'Era retirado antes de aguardar no painel.',
    explanation: 'O dispensador de bilhetes numerados organiza a fila de atendimento.',
  },
  {
    answer: 'painel de senha',
    aliases: ['painel eletronico de senha', 'chamador de senha'],
    evidence: 'a wall-mounted red LED queue display glowing above rows of empty plastic chairs',
    contextualHint: 'Um numero vermelho chamava alguem que ja havia ido embora.',
    technicalHint: 'O painel orientava a fila de atendimento.',
    nearAnswerHint: 'A senha aparecia em LEDs vermelhos.',
    explanation: 'O mostrador vermelho sobre cadeiras de espera e um painel de senha.',
  },
  {
    answer: 'carimbo',
    aliases: ['carimbo de borracha', 'carimbo datador'],
    evidence: 'a rubber date stamp beside an ink pad and a stack of blank administrative forms',
    contextualHint: 'A reparticao confiava em um pequeno impacto oficial.',
    technicalHint: 'Tinta e pressao validavam a passagem de um documento.',
    nearAnswerHint: 'A data podia ser ajustada manualmente antes de carimbar.',
    explanation: 'A ferramenta com almofada de tinta e um carimbo de reparticao.',
  },
  {
    answer: 'autenticadora bancaria',
    aliases: ['autenticadora', 'maquina autenticadora'],
    evidence: 'a bank validation machine beside a stack of payment receipts with blurred markings',
    contextualHint: 'O pagamento precisava deixar uma marca mecanica.',
    technicalHint: 'A maquina imprimia validacao diretamente no documento.',
    nearAnswerHint: 'Era comum no caixa bancario para autenticar comprovantes.',
    explanation: 'A maquina de balcão que imprime validacoes e uma autenticadora bancaria.',
  },
  {
    answer: 'calculadora de mesa',
    aliases: ['calculadora com bobina', 'calculadora impressora'],
    evidence: 'a desktop printing calculator with a narrow paper roll and oversized keys',
    contextualHint: 'As contas deixavam um rastro de papel.',
    technicalHint: 'Cada operacao podia ser impressa em uma bobina estreita.',
    nearAnswerHint: 'Era uma calculadora de mesa com impressora.',
    explanation: 'A calculadora de teclas grandes com bobina registrava contas em papel.',
  },
  {
    answer: 'mimeografo',
    aliases: ['mimeografo a alcool', 'mimeografo escolar'],
    evidence: 'an old manual duplicating machine with a side crank and a stack of pale copies',
    contextualHint: 'O corredor escolar ainda parecia guardar um cheiro doce de alcool.',
    technicalHint: 'Uma manivela multiplicava folhas antes das copiadoras comuns.',
    nearAnswerHint: 'Muitas provas escolares sairam de um mimeografo.',
    explanation: 'A duplicadora manual com manivela e um mimeografo.',
  },
  {
    answer: 'retroprojetor',
    aliases: ['projetor de transparencias', 'overhead projector'],
    evidence: 'an overhead projector with its glass stage empty and power cord loosely wound',
    contextualHint: 'A apresentacao dependia de folhas transparentes.',
    technicalHint: 'A luz projetava o que era colocado sobre uma superficie de vidro.',
    nearAnswerHint: 'Ele antecedeu o projetor digital nas salas de aula.',
    explanation: 'O equipamento com base iluminada e haste e um retroprojetor.',
  },
  {
    answer: 'maquina de escrever',
    aliases: ['datilografo', 'maquina datilografica'],
    evidence: 'a manual typewriter with one blank sheet rolled into the carriage',
    contextualHint: 'Nenhuma tecla era silenciosa e nenhum erro desaparecia facilmente.',
    technicalHint: 'Tipos mecanicos golpeavam uma fita entintada.',
    nearAnswerHint: 'O texto era datilografado diretamente no papel.',
    explanation: 'O teclado mecanico com carro e fita e uma maquina de escrever.',
  },
  {
    answer: 'secretaria eletronica',
    aliases: ['atendedor automatico', 'answering machine'],
    evidence: 'a telephone answering machine with a tiny red message counter and cassette compartment',
    contextualHint: 'Uma luz vermelha dizia que alguem tentou falar com a sala vazia.',
    technicalHint: 'O aparelho gravava recados quando a ligacao nao era atendida.',
    nearAnswerHint: 'Ficava ao lado do telefone fixo.',
    explanation: 'O contador de mensagens e o compartimento de fita apontam para uma secretaria eletronica.',
  },
  {
    answer: 'telefone sem fio',
    aliases: ['telefone cordless', 'cordless'],
    evidence: 'a yellowed cordless landline handset resting beside, not on, its charging base',
    contextualHint: 'A ligacao podia caminhar alguns metros pela casa.',
    technicalHint: 'A base permanecia conectada a linha telefonica.',
    nearAnswerHint: 'O monofone nao precisava de fio durante a conversa.',
    explanation: 'O monofone separado de sua base carregadora e um telefone sem fio.',
  },
  {
    answer: 'agenda eletronica',
    aliases: ['organizer', 'pda simples'],
    evidence: 'a pocket electronic organizer with a small monochrome LCD and miniature keyboard',
    contextualHint: 'Compromissos inteiros dormiam em uma tela sem iluminacao.',
    technicalHint: 'O aparelho guardava contatos, agenda e notas.',
    nearAnswerHint: 'Era uma agenda eletronica de bolso.',
    explanation: 'O aparelho de bolso com visor monocromatico e teclado pequeno e uma agenda eletronica.',
  },
  {
    answer: 'palm pilot',
    aliases: ['palm', 'pda', 'palmtop'],
    evidence: 'a Palm handheld PDA with its stylus resting in the groove beside the grayscale screen',
    contextualHint: 'A tela esperava uma caneta que nao usava tinta.',
    technicalHint: 'O organizador de bolso reconhecia gestos feitos com stylus.',
    nearAnswerHint: 'A linha Palm popularizou esse tipo de PDA.',
    explanation: 'O PDA com stylus e tela cinza e um Palm Pilot.',
  },
  {
    answer: 'celular tijolao',
    aliases: ['tijolao', 'celular analogico', 'telefone celular antigo'],
    evidence: 'a large early mobile phone with a long antenna resting near a security desk',
    contextualHint: 'Ser movel ainda significava carregar peso.',
    technicalHint: 'A antena longa e o corpo espesso pertencem ao inicio da telefonia celular.',
    nearAnswerHint: 'O apelido brasileiro lembrava um bloco de construcao.',
    explanation: 'O aparelho grande com antena longa e um celular tijolao.',
  },
  {
    answer: 'nextel',
    aliases: ['radio nextel', 'push to talk', 'ptt'],
    evidence: 'a rugged push-to-talk mobile handset in a charging cradle beside a dispatch notebook',
    contextualHint: 'A conversa chegava em rajadas curtas de trabalho.',
    technicalHint: 'Um botao lateral transformava o aparelho em radio.',
    nearAnswerHint: 'O servico ficou conhecido pelo nome Nextel.',
    explanation: 'O aparelho robusto com botao push-to-talk remete aos radios Nextel.',
  },
  {
    answer: 'radio am fm',
    aliases: ['radio portatil', 'radio transistor'],
    evidence: 'a portable AM/FM radio with a telescopic antenna and analog tuning dial',
    contextualHint: 'Uma frequencia podia preencher a sala sem precisar de internet.',
    technicalHint: 'O ajuste analogico percorria faixas AM e FM.',
    nearAnswerHint: 'A antena telescopica procurava emissoras.',
    explanation: 'O aparelho com dial analogico e antena e um radio AM/FM.',
  },
  {
    answer: 'radio relogio',
    aliases: ['relogio despertador', 'clock radio'],
    evidence: 'a bedside clock radio showing dim red segmented digits on an empty reception counter',
    contextualHint: 'A madrugada tinha numeros vermelhos e uma emissora quase fora do ar.',
    technicalHint: 'O aparelho unia despertador digital e sintonia de radio.',
    nearAnswerHint: 'Os digitos vermelhos eram comuns em radios-relogio.',
    explanation: 'O mostrador vermelho e os controles de sintonia indicam um radio-relogio.',
  },
  {
    answer: 'gravador de fita',
    aliases: ['gravador cassete', 'tape recorder'],
    evidence: 'a portable cassette recorder with mechanical buttons and an external microphone jack',
    contextualHint: 'A sala poderia arquivar a propria ausencia.',
    technicalHint: 'Os botoes mecanicos controlavam uma fita magnetica.',
    nearAnswerHint: 'Ele gravava audio em cassete.',
    explanation: 'O aparelho portatil com botoes mecanicos e compartimento de fita e um gravador cassete.',
  },
  {
    answer: 'microcassete',
    aliases: ['microcassette', 'fita de secretaria eletronica'],
    evidence: 'a tiny microcassette next to an office dictation recorder',
    contextualHint: 'A voz precisava caber em uma fita ainda menor.',
    technicalHint: 'Era comum em gravadores de ditado e secretarias eletronicas.',
    nearAnswerHint: 'O nome descreve uma cassete em miniatura.',
    explanation: 'A fita magnetica diminuta e uma microcassete.',
  },
  {
    answer: 'cartao perfurado',
    aliases: ['punch card', 'cartao de perfuracao'],
    evidence: 'a single punched card with rows of holes lying inside a metal archive drawer',
    contextualHint: 'Os dados aparecem como ausencias cuidadosamente posicionadas.',
    technicalHint: 'Cada furo podia representar informacao para processamento.',
    nearAnswerHint: 'Computadores antigos liam cartoes perfurados.',
    explanation: 'A cartolina com linhas de furos e um cartao perfurado de processamento de dados.',
  },
  {
    answer: 'microfilme',
    aliases: ['microfilmagem', 'rolo de microfilme'],
    evidence: 'a small reel of microfilm beside a library archive reader',
    contextualHint: 'Anos de documentos foram reduzidos ate quase desaparecer.',
    technicalHint: 'Paginas fotografadas em miniatura economizavam espaco de arquivo.',
    nearAnswerHint: 'Era preciso um leitor para consultar o microfilme.',
    explanation: 'O pequeno rolo junto ao leitor de arquivo e um microfilme.',
  },
  {
    answer: 'leitor de microfilme',
    aliases: ['leitora de microfilme', 'microfilm reader'],
    evidence: 'a bulky archive microfilm reader with an empty illuminated viewing screen',
    contextualHint: 'A tela servia para ampliar memorias reduzidas.',
    technicalHint: 'O equipamento projetava documentos fotografados em rolo.',
    nearAnswerHint: 'Ele permitia consultar microfilmes.',
    explanation: 'A maquina de consulta de arquivo com tela iluminada e um leitor de microfilme.',
  },
  {
    answer: 'terminal de ponto',
    aliases: ['relogio de ponto', 'ponto eletronico', 'relógio de ponto'],
    evidence: 'an early electronic time-clock terminal beside a rack of unused employee cards',
    contextualHint: 'A empresa fechou, mas a entrada ainda esperava registrar horario.',
    technicalHint: 'O aparelho marcava a chegada e a saida de funcionarios.',
    nearAnswerHint: 'Era usado para bater o ponto.',
    explanation: 'O equipamento na entrada com cartoes de horario e um terminal de ponto.',
  },
  {
    answer: 'bilhete unico',
    aliases: ['cartao bilhete unico', 'cartao de transporte'],
    evidence: 'a worn transit smart card on a wet turnstile ledge, markings out of focus',
    contextualHint: 'Uma viagem urbana inteira cabia num cartao gasto.',
    technicalHint: 'O credito liberava a catraca do transporte publico.',
    nearAnswerHint: 'Em Sao Paulo, o cartao ficou conhecido como Bilhete Unico.',
    explanation: 'O cartao sobre a catraca aponta para o Bilhete Unico de transporte urbano.',
  },
  {
    answer: 'vale transporte',
    aliases: ['vt', 'vale-transporte', 'ficha de onibus'],
    evidence: 'a small stack of old paper transit vouchers beside a bus-terminal change window',
    contextualHint: 'O trajeto para o trabalho era contado em pequenos vales.',
    technicalHint: 'Antes da recarga eletronica, o beneficio podia circular em papel ou ficha.',
    nearAnswerHint: 'O empregador fornecia vale-transporte.',
    explanation: 'Os pequenos vales no guiche do terminal representam o vale-transporte antigo.',
  },
  {
    answer: 'titulo de eleitor',
    aliases: ['titulo eleitoral', 'documento eleitoral'],
    evidence: 'an old folded voter registration document partly visible beneath a plastic service-window tray',
    contextualHint: 'A cidadania tambem esperava sua vez no guiche.',
    technicalHint: 'O documento registrava zona e secao para uma obrigacao periodica.',
    nearAnswerHint: 'Era apresentado na epoca de votacao.',
    explanation: 'O pequeno documento dobravel de reparticao eleitoral e um titulo de eleitor antigo.',
  },
  {
    answer: 'cpf de papel',
    aliases: ['cartao cpf', 'cpf azul', 'cadastro de pessoa fisica'],
    evidence: 'a small blue paper tax-registration card in a cracked transparent sleeve',
    contextualHint: 'Um numero permanente sobreviveu em um cartao fragil.',
    technicalHint: 'O cadastro fiscal brasileiro ja foi entregue em cartao separado.',
    nearAnswerHint: 'Antes de aparecer em outros documentos, havia o CPF de papel.',
    explanation: 'O pequeno cartao azul em plastico e o antigo CPF de papel.',
  },
  {
    answer: 'carteira de trabalho',
    aliases: ['ctps', 'carteira profissional'],
    evidence: 'a worn blue employment booklet closed on an empty human-resources counter',
    contextualHint: 'A vida profissional deixava marcas em paginas fisicas.',
    technicalHint: 'Contratos e anotacoes de emprego eram registrados em uma caderneta.',
    nearAnswerHint: 'A sigla oficial e CTPS.',
    explanation: 'A caderneta azul sobre o balcão de RH e uma carteira de trabalho.',
  },
  {
    answer: 'telegrama',
    aliases: ['telegrama dos correios', 'mensagem telegrafica'],
    evidence: 'a sealed postal telegram envelope in a sorting tray, with all writing blurred',
    contextualHint: 'A urgencia chegava em poucas palavras e papel oficial.',
    technicalHint: 'Os Correios entregavam a mensagem curta ao destinatario.',
    nearAnswerHint: 'Era mais rapido e solene que uma carta.',
    explanation: 'O envelope oficial de mensagem urgente remete ao telegrama.',
  },
]

if (subjects.length !== 60) {
  throw new Error(`Expected 60 mystery subjects, received ${subjects.length}.`)
}
